# Generated by Django 5.1.7 on 2025-03-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_usuario_es_administrador_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=10),
        ),
    ]
